### ISSUE TITLE
pip install error on MacOS Ventura 13.5.2

### ISSUE THREAD

**Issue by victoreguevara** [ondrolexa/pywerami#2]
Using Python 3.11.5:

victorguevara@GEOL-ML-015082 ~ % pip install pywerami
Collecting pywerami
  Obtaining dependency information for pywerami from https://files.pythonhosted.org/packages/1c/3b/b73d2ef4fec56a5767847048e9cc5eebe773c2ccfd68fb7292c1a6c738d8/pywerami-0.2.7-py2.py3-none-any.whl.metadata
  Using cached pywerami-0.2.7-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting PyQt5 (from pywerami)
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/kp/dmm_z5795znd84n_44mygqfc0000gq/T/pip-build-env-qxtwul_3/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/kp/dmm_z5795znd84n_44mygqfc0000gq/T/pip-build-env-qxtwul_3/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/kp/dmm_z5795znd84n_44mygqfc0000gq/T/pip-build-env-qxtwul_3/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/kp/dmm_z5795znd84n_44mygqfc0000gq/T/pip-install-qkn83wh4/pyqt5_e1b989e892954f31a801898b5f082998/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/kp/dmm_z5795znd84n_44mygqfc0000gq/T/pip-build-env-qxtwul_3/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/kp/dmm_z5795znd84n_44mygqfc0000gq/T/pip-build-env-qxtwul_3/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/kp/dmm_z5795znd84n_44mygqfc0000gq/T/pip-build-env-qxtwul_3/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ondrolexa** [comment]
You need to have Qt5 installed in the system, and you need to have its `qmake` in PATH.

To install Qt5, you can either run `brew install qt5` or download the installer from https://www.qt.io/download-qt-installer.

After the installation, find where `qmake` is located, e.g. `/Users/Admin/Qt5.14.2/5.14.2/clang_64/bin`. You need to add this to the PATH environment variable. To do so edit .bash_profile in your home folder (may need to press Command + Shift + . first to see dotfiles in Finder) and add to it something the following:

```
export PATH="$PATH:/Users/Admin/Qt5.14.2/5.14.2/clang_64/bin"
```

Now, upon launching a new terminal, you should be able to install pywerami.
